### PR TITLE
implement offset and at

### PR DESCRIPTION
**Pull request by stereomatchingkiss**
I implement the offset and at functions of 2d dimensions, if you think these codes meet your requirements, I will continue with 3 and 4 dimensions.

### CODE REVIEW

**Comment by stereomatchingkiss** [comment]
This one haven't finished yet, there are 3 dimensions and 4 dimensions case haven't handle.

What I want to ask is, what kind of layout mxnet prefer?Assume I am reading an color image by opencv, default layout will be

bgr bgr bgr bgr
bgr bgr bgr bgr
.......................
.......................
bgr bgr bgr bgr

I think many of the computer vision tasks would depend on opencv, 
follow the convention of opencv maybe a better way, what is your opinion?
Thanks

**Comment by stereomatchingkiss** [comment]
What kind of layout you prefer?

Assume you are reading a 2*2, 3 channels image by opencv, the layout will be

bgr bgr
bgr bgr

Or you prefer layout like this

channel 0
b b
b b

channel 1
g g
g g

channel 2
r r
r r

After you decided, I will begin the implementation of 3 and 4 channels offset

**Comment by hjk41** [comment]
The layout depends on how the input was generated, right? The goal of
offset() and at() is to provide a way for the user to disregard the
ColumnMajor or RowMajor layout, which user does not know when getting the
pointer returned by Data(). But user has to know the dimensions of the
NDArray in order to access the element.

On Wed, Feb 3, 2016 at 4:50 AM, stereomatchingkiss <notifications@github.com
> wrote:

> What kind of layout you prefer?
>
> Assume you are reading a 2*2, 3 channels image by opencv, the layout will
> be
>
> bgr bgr
> bgr bgr
>
> Or you prefer layout like this
>
> channel 0
> b b
> b b
>
> channel 1
> g g
> g g
>
> channel 2
> r r
> r r
>
> After you decided, I will begin the implementation of 3 and 4 channels
> offset
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/pull/15#issuecomment-178812865>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by stereomatchingkiss** [comment]
>The layout depends on how the input was generated, right?
Yeah, looks like I do not need to care about it

**Pull request merged**
