### PR TITLE
simple bind and more; make the header library; lenet example

### PR DESCRIPTION
**Pull request by zhangchen-qinyinghua**
I add some functions including the SimpleBind, and a Lenet example.
Please check the codes.

### CODE REVIEW

**Comment by hjk41** [comment]
@zhangchen-qinyinghua Looks good. Could you add some comments to the methods?

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
Sure, I will add the comments a.s.a.p.

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
I think we should wait for the NDArray to be initialized?

**Comment by hjk41** [comment]
I think the dependency engine should guarantee the correctness of the
content, unless we are accessing the raw memory of the NDArrays outside
MxNet.

On Mon, Jan 18, 2016 at 2:41 PM, Zhang Chen <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41>
> I think we should wait for the NDArray to be initialized?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hjk41/MxNet.cpp/pull/9#issuecomment-172441482>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
I think you are right.
I try to remove some of the WaitAll(), and it works.
It seems that we only need WaitAll() when we are doing some copy of the data(from CPU to GPU and vise versa).

**Comment by zhangchen-qinyinghua** [comment]
PR will be made tonight on commenting and removing the unnecessary WaitAll.

**Pull request merged**
